# Generated by Django 5.1.4 on 2025-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0002_monthlydata_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlydata',
            name='user',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='MonthlyData',
        ),
    ]
