# Generated by Django 5.1.4 on 2025-01-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0004_monthlydata_income_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlydata',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='MonthlyData',
        ),
    ]
