# Generated by Django 5.1.4 on 2025-02-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0006_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_at',
        ),
    ]
