# Generated by Django 5.1.4 on 2025-02-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0008_remove_income_user_expensesource_incomesource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesource',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='incomesource',
            name='amount',
        ),
        migrations.AlterField(
            model_name='expensesource',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expensesource',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=20),
        ),
    ]
