# Generated by Django 5.1.4 on 2025-02-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0009_remove_expensesource_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseSource',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
    ]
