# Generated by Django 5.1.4 on 2025-02-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0011_expensesource_incomesource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomesource',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseSource',
        ),
        migrations.DeleteModel(
            name='IncomeSource',
        ),
    ]
