# Generated by Django 5.1.4 on 2025-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0013_expense_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Expensename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Incomename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='emoji',
            field=models.CharField(default='💸', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='emoji',
            field=models.CharField(default='💰', max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one-time', 'One-time')], max_length=50),
        ),
    ]
