# Generated by Django 5.1.4 on 2025-02-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0015_remove_expense_currency_remove_expense_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='emoji',
            field=models.CharField(default='🛒', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='emoji',
            field=models.CharField(default='💰', max_length=100),
        ),
    ]
