# Generated by Django 5.1.4 on 2025-02-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WW', '0017_currency_remove_expense_source_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
